# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6ebe49fb929f5e3b8a192e917e2effb2bd9dedc0b0d2c41b9c9818ccdcc8e1fc43c9d31dd8c5af7465415c1ba921479722cdcc117c69f7440b47a35b3021191

test:
  secret_key_base: bb173c01c41f902d321e23b0d0d089a083a9fc18c447cd9db657d85e068430fb6d0bd26596e61650ba754779e42976172e588eece78d29bab3a0282c62907008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
